### ISSUE TITLE
Utilize GitHub Actions substitution rules

### ISSUE THREAD

**Issue by prince-chrismc** [prince-chrismc/label-merge-conflicts-action#301]
Instead of having special support for the github action, it would be nice to do

the same as https://github.com/actions-ecosystem/action-create-comment

```yml
      - uses: actions-ecosystem/action-create-comment@v1
        if: ${{ startsWith(github.event.comment.body, '/hello') }}
        with:
          github_token: ${{ secrets.github_token }}
          body: |
            Hello, @${{ github.actor }}!
```
